VEHICLE_SIRENS = {
    [`DEFAULT`] = { 'VEHICLES_HORNS_SIREN_1', 'VEHICLES_HORNS_SIREN_2', 'VEHICLES_HORNS_POLICE_WARNING' },
    [`FIRETRUK`] = { 'RESIDENT_VEHICLES_SIREN_FIRETRUCK_WAIL_01', 'RESIDENT_VEHICLES_SIREN_FIRETRUCK_QUICK_01', 'VEHICLES_HORNS_AMBULANCE_WARNING' },
    [`AMBULANCE`] = { 'VEHICLES_HORNS_SIREN_1', 'VEHICLES_HORNS_SIREN_2', 'VEHICLES_HORNS_POLICE_WARNING', 'VEHICLES_HORNS_AMBULANCE_WARNING' },
    [`LGUARD`] = { 'VEHICLES_HORNS_SIREN_1', 'VEHICLES_HORNS_SIREN_2', 'VEHICLES_HORNS_POLICE_WARNING', 'VEHICLES_HORNS_AMBULANCE_WARNING' }
}

VEHICLE_HORNS = {
    [`DEFAULT`] = 'SIRENS_AIRHORN',
    [`FIRETRUK`] = 'VEHICLES_HORNS_FIRETRUCK_WARNING'
}

HEAVY_CLEANUP_TIME_IN_MS = 30 * 1000
EMERGENCY_VEHICLE_CLASS = 18